=== Vranjan7077/JMI_MCA1921/MCA-4th-Sem/IVth Semester/J2EE/Assignments/Assignment 2/ASS2 NodeView/rec.dtd
<!ELEMENT record (student+)>
<!ELEMENT student (name,course,semester,state,email,mobile)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT course (#PCDATA)>
<!ELEMENT semester (#PCDATA)>
<!ELEMENT state (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT mobile (#PCDATA)>

=== Vranjan7077/JMI_MCA1921/MCA-4th-Sem/IVth Semester/J2EE/Assignments/Assignment 2/ASS2/ASS2 TableView/Config.xml
<?xml version="1.0" ?>
<!DOCTYPE record SYSTEM "rec.dtd">

<record>
	<student>
		<name>Sanjeev Kumar</name>
		<course>MCA</course>
		<semester>4th</semester>
		<state>Uttar Pradesh</state>
		<email>sanjeevbiswas.10@gmail.com</email>
		<mobile>9598341156</mobile>
	</student>
	<student>
		<name>Ranit Biswas</name>
		<course>MCA</course>
		<semester>4th</semester>
		<state>Delhi</state>
		<email>ranit.vishwas@gmail.com</email>
		<mobile>8400004520</mobile>
	</student>
</record>
